sudo: false

env:
  global:
  - CC_TEST_REPORTER_ID=95ee07c1adee34e888512de464dc031d94353db56566098f25e0f50783565e8d

language: php

php:
- 7.1
- 7.2

before_script:
- composer install
- mkdir -p build
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- composer test-coverage
- composer cs-check

after_success:
- travis_retry composer upload-coverage

after_script:
- mv build/clover.xml clover.xml
- ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
